service:
    path:  /
    defaults: { _controller: "ServiceBundle:Service:index" }

service_sort:
    path:  /{field}/{type}/sort
    defaults: { _controller: "ServiceBundle:Service:sort" }
    requirements: { type: ASC|DESC }

service_show:
    path:  /{id}/show
    defaults: { _controller: "ServiceBundle:Service:show" }

service_new:
    path:  /new
    defaults: { _controller: "ServiceBundle:Service:new" }

service_create:
    path:  /create
    defaults: { _controller: "ServiceBundle:Service:create" }
    requirements: { _method: post }

service_edit:
    path:  /{id}/edit
    defaults: { _controller: "ServiceBundle:Service:edit" }

service_update:
    path:  /{id}/update
    defaults: { _controller: "ServiceBundle:Service:update" }
    requirements: { _method: post|put }

service_delete:
    path:  /{id}/delete
    defaults: { _controller: "ServiceBundle:Service:delete" }
    requirements: { _method: post|delete }
