formation_homepage:
    path:     /
    defaults: { _controller: FormationBundle:Default:index }
formation_aboutus:
    path:     /aboutus
    defaults: { _controller: FormationBundle:Default:aboutus }
formation_services:
    path:     /services
    defaults: { _controller: FormationBundle:Default:services }
formation_gallery:
    path:     /gallery
    defaults: { _controller: FormationBundle:Default:gallery }
formation_contactus:
    path:     /contactus
    defaults: { _controller: FormationBundle:Default:aboutus }
