evenement_index:
    path:     /
    defaults: { _controller: "FixitBundle:evenement:index" }
    methods:  GET
evenement_index1:
        path:     /1
        defaults: { _controller: "FixitBundle:evenement:index1" }
        methods:  GET
evenement_index2:
    path:     /2
    defaults: { _controller: "FixitBundle:evenement:index2" }
    methods:  GET
evenement_show:
    path:     /{id}/show
    defaults: { _controller: "FixitBundle:evenement:show" }
    methods:  GET
evenement_show1:
    path:     /{id}/show1
    defaults: { _controller: "FixitBundle:evenement:show1" }
    methods:  GET
evenement_show2:
    path:     /{id}/show2
    defaults: { _controller: "FixitBundle:evenement:show2" }
    methods:  GET
evenement_new:
    path:     /new
    defaults: { _controller: "FixitBundle:evenement:new" }
    methods:  [GET, POST]
evenement_new2:
    path:     /new2
    defaults: { _controller: "FixitBundle:evenement:new2" }
    methods:  [GET, POST]
evenement_edit:
    path:     /{id}/edit
    defaults: { _controller: "FixitBundle:evenement:edit" }
    methods:  [GET, POST]
evenement_edit2:
    path:     /{id}/edit2
    defaults: { _controller: "FixitBundle:evenement:edit2" }
    methods:  [GET, POST]
evenement_delete:
    path:     /{id}/delete
    defaults: { _controller: "FixitBundle:evenement:delete" }
    methods:  DELETE
evenement_delete2:
    path:     /{id}/delete2
    defaults: { _controller: "FixitBundle:evenement:delete2" }
    methods:  DELETE