entrepreneur:
    resource: "@EntrepreneurBundle/Resources/config/routing.yml"
    prefix:   /entrep

cabinet:
    resource: "@CabinetBundle/Resources/config/routing.yml"
    prefix:   /cabinet

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

pro:
    resource: "@ProBundle/Resources/config/routing.yml"
    prefix:   /pro

client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /client

fixit:
    resource: "@FixitBundle/Resources/config/routing.yml"
    prefix:   /fixit

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

