<?php

namespace EntrepreneurBundle\Repository;

/**
 * EquipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipesRepository extends \Doctrine\ORM\EntityRepository
{
}
