service_service:
    resource: "@ServiceBundle/Resources/config/routing/service.yml"
    prefix:   /service

service_homepage:
    path:     /
    defaults: { _controller: ServiceBundle:Default:index }
